compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
num_processes: 4
mixed_precision: bf16
downcast_bf16: "no"
deepspeed_config:
  zero_stage: 2
  offload_optimizer_device: none
  offload_param_device: none
  train_micro_batch_size_per_gpu: 2
  zero3_init_flag: false
  zero3_save_16bit_model: false
main_training_function: main
