from __future__ import annotations

import gzip
import json
import os
from pathlib import Path
from typing import Any

from .generation import action_from_transport, action_to_transport
from .workflow import CreditConfig, centered_advantages, stage_returns


def trajectory_to_record(trajectory, *, root_index: int, task_id: str, worker_rank: int) -> dict[str, Any]:
    return {
        "task_id": task_id,
        "root_index": int(root_index),
        "sample_id": str(trajectory.sample_id),
        "rollout_index": int(trajectory.rollout_index),
        "gt_image_path": str(trajectory.gt_image_path),
        "worker_rank": int(worker_rank),
        "stage0": action_to_transport(trajectory.stage0),
        "stage1": action_to_transport(trajectory.stage1),
        "stage0_ok": bool(trajectory.stage0_ok),
        "stage1_ok": bool(trajectory.stage1_ok),
        "stage0_score": float(trajectory.stage0_score),
        "stage1_score": float(trajectory.stage1_score),
        "delta_score": float(trajectory.delta_score),
        "route": str(trajectory.route),
        "stage0_error": trajectory.stage0_env.render.error,
        "stage1_error": trajectory.stage1_env.render.error,
        "stage0_png_path": trajectory.stage0_env.render.png_path,
        "stage1_png_path": trajectory.stage1_env.render.png_path,
        "stage0_tikz_hash": trajectory.stage0_env.render.code_hash,
        "stage1_tikz_hash": trajectory.stage1_env.render.code_hash,
        "stage0_return": float(getattr(trajectory, "stage0_return", 0.0)),
        "stage1_return": float(getattr(trajectory, "stage1_return", 0.0)),
        "stage0_advantage": float(getattr(trajectory, "stage0_advantage", 0.0)),
        "stage1_advantage": float(getattr(trajectory, "stage1_advantage", 0.0)),
    }


def write_record_atomic(path: str | Path, record: dict[str, Any]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + f".tmp.{os.getpid()}")
    with gzip.open(tmp, "wt", encoding="utf-8") as handle:
        json.dump(record, handle, ensure_ascii=False, separators=(",", ":"))
    os.replace(tmp, path)


def read_record(path: str | Path) -> dict[str, Any]:
    with gzip.open(path, "rt", encoding="utf-8") as handle:
        return json.load(handle)


def assign_group_credit(records: list[dict[str, Any]], group_size: int, scale: float) -> None:
    """Assign return/advantage in-place after globally distributed rollout.

    Grouping is by ``root_index`` and ``rollout_index`` rather than physical
    worker rank, so a G=8 root may be generated by any mixture of workers.
    """
    by_root: dict[int, list[dict[str, Any]]] = {}
    for record in records:
        by_root.setdefault(int(record["root_index"]), []).append(record)
    cfg = CreditConfig(scale=float(scale))
    for root_index, group in by_root.items():
        group.sort(key=lambda row: int(row["rollout_index"]))
        if len(group) != int(group_size):
            raise RuntimeError(
                f"root_index={root_index} has {len(group)} trajectories, expected G={group_size}"
            )
        returns0: list[float] = []
        returns1: list[float] = []
        for row in group:
            r0, r1 = stage_returns(float(row["stage0_score"]), float(row["stage1_score"]), cfg)
            returns0.append(r0)
            returns1.append(r1)
        advantages0 = centered_advantages(returns0)
        advantages1 = centered_advantages(returns1)
        for row, r0, r1, a0, a1 in zip(
            group, returns0, returns1, advantages0, advantages1, strict=True
        ):
            row["stage0_return"] = float(r0)
            row["stage1_return"] = float(r1)
            row["stage0_advantage"] = float(a0)
            row["stage1_advantage"] = float(a1)


def materialize_stage_actions(
    records: list[dict[str, Any]], stage: int, processor
) -> tuple[list[Any], list[float]]:
    key = f"stage{int(stage)}"
    advantage_key = f"stage{int(stage)}_advantage"
    actions = [action_from_transport(row[key], processor) for row in records]
    advantages = [float(row[advantage_key]) for row in records]
    return actions, advantages


def record_cost(record: dict[str, Any], stage: int) -> int:
    payload = record[f"stage{int(stage)}"]
    prompt_len = int(payload.get("prompt_len", 0))
    completion_len = len(payload.get("completion_ids", []))
    return prompt_len + completion_len


def balanced_fixed_count_partition(
    records: list[dict[str, Any]], world_size: int, stage: int
) -> list[list[dict[str, Any]]]:
    """Deterministic LPT-style token-balanced partition with equal item counts.

    Equal counts preserve an identical number of loss microbatches/backward
    calls on every DDP rank; the LPT assignment reduces full-sequence padding
    and rank-level backward stragglers.
    """
    world_size = int(world_size)
    if world_size <= 0 or len(records) % world_size != 0:
        raise ValueError("record count must be divisible by world_size")
    capacity = len(records) // world_size
    bins: list[list[dict[str, Any]]] = [[] for _ in range(world_size)]
    totals = [0 for _ in range(world_size)]
    ordered = sorted(
        records,
        key=lambda row: (
            -record_cost(row, stage),
            int(row["root_index"]),
            int(row["rollout_index"]),
        ),
    )
    for row in ordered:
        candidates = [r for r in range(world_size) if len(bins[r]) < capacity]
        target = min(candidates, key=lambda r: (totals[r], len(bins[r]), r))
        bins[target].append(row)
        totals[target] += record_cost(row, stage)
    return bins
